services:
    sf.compiler.event:
        class: Symforce\CoreBundle\Event\SymforceEventCompiler

    sf.event.tester:
        class: Symforce\CoreBundle\Event\SymforceEventBuilder
        tags:
            - { name: "sf.event.builder", alias: as_1 }
